stages:
  jewewlry: 
    cmd: >
      kaggle datasets download mkechinov/ecommerce-purchase-history-from-jewelry-store
      --unzip
      -p data/external/jewelry
    outs:
    - data/external/jewelry

  journey: 
    cmd: >
      kaggle datasets download frtgnn/dunnhumby-the-complete-journey
      --unzip
      -p data/external/journey
    outs:
    - data/external/journey

  electronics: 
    cmd: >
      kaggle datasets download mkechinov/ecommerce-purchase-history-from-electronics-store
      --unzip
      -p data/external/electronics
    outs:
    - data/external/electronics

  brazil:
    cmd: >
      kaggle datasets download olistbr/brazilian-ecommerce
      --unzip
      -p data/external/brazilian
    outs:
    - data/external/brazilian

  ecommerce:
    cmd: >
      kaggle datasets download -d carrie1/ecommerce-data
      --unzip
      -p data/external/ecommerce
    outs:
    - data/external/ecommerce

  retail_ecommerce:
    cmd: >
      kaggle datasets download -d retailrocket/ecommerce-dataset
      --unzip
      -p data/external/retailrocket
    outs:
    - data/external/retailrocket

  vipin20:
    cmd: >
      kaggle datasets download -d vipin20/transaction-data
      --unzip
      -p data/external/vipin20
    outs:
    - data/external/vipin20

  data:
    cmd: echo "Pulling all data"
    deps:
    - data/external/electronics
    - data/external/brazilian
    - data/external/ecommerce
    - data/external/retailrocket
    - data/external/vipin20
    - data/external/jewelry
    - data/external/journey

  ecommerce_implicit_eda:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute ECommerce-Implicit-EDA.ipynb
    deps:
    - notebooks/ECommerce-Implicit-EDA.ipynb
    - data/external/ecommerce/data.csv
    outs:
    - data/interim/ecommerce/item_lookup.gz  
    - data/interim/ecommerce/item_lookup.csv  
    - data/interim/ecommerce/selected_invoices.gz  
    - data/interim/ecommerce/selected_invoices.csv  

  ecommerce_implicit_recommendation:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute ECommerce-Implicit-Recommendation.ipynb
    deps:
    - notebooks/ECommerce-Implicit-Recommendation.ipynb
    - data/interim/ecommerce/selected_invoices.gz
    outs:
    - data/interim/ecommerce/user_factors.npy  
    - data/interim/ecommerce/item_factors.npy
    - data/interim/ecommerce/product_train.npy

  vipin20_implicit_eda:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute vipin20-Transaction-Data-EDA.ipynb
    deps:
    - notebooks/vipin20-Transaction-Data-EDA.ipynb
    - data/external/vipin20/transaction_data.csv
    outs:
    - data/interim/vipin20/transactions.gz  

  vipin20_implicit_recommendation:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute vipin20-Implicit-Recommendation.ipynb
    deps:
    - notebooks/vipin20-Implicit-Recommendation.ipynb
    - data/interim/vipin20/transactions.gz
    outs:
    - data/interim/vipin20/user_factors.npy  
    - data/interim/vipin20/item_factors.npy
    - data/interim/vipin20/product_train.npy

  jewelry_implicit_eda:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute jewelry-EDA.ipynb
    deps:
    - notebooks/jewelry-EDA.ipynb
    - data/external/jewelry
    outs:
    - data/interim/jewelry/transactions.gz
