stages:
  electronics: 
    cmd: >
      kaggle datasets download mkechinov/ecommerce-purchase-history-from-electronics-store
      --unzip
      -p data/external/ecommerce-purchase-history-from-electronics-store/.
    outs:
    - data/external/ecommerce-purchase-history-from-electronics-store

  brazil:
    cmd: >
      kaggle datasets download olistbr/brazilian-ecommerce
      --unzip
      -p data/external/brazilian-ecommerce
    outs:
    - data/external/brazilian-ecommerce

  ecommerce:
    cmd: >
      kaggle datasets download -d carrie1/ecommerce-data
      --unzip
      -p data/external/ecommerce
    outs:
    - data/external/ecommerce

  retail_ecommerce:
    cmd: >
      kaggle datasets download -d retailrocket/ecommerce-dataset
      --unzip
      -p data/external/ecommerce-dataset
    outs:
    - data/external/ecommerce-dataset

  vipin20:
    cmd: >
      kaggle datasets download -d vipin20/transaction-data
      --unzip
      -p data/external/vipin20
    outs:
    - data/external/vipin20

  data:
    cmd: echo "Pulling all data"
    deps:
    - data/external/ecommerce-purchase-history-from-electronics-store
    - data/external/brazilian-ecommerce
    - data/external/ecommerce
    - data/external/ecommerce-dataset
    - data/external/vipin20

  ecommerce_implicit_eda:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute ECommerce-Implicit-EDA.ipynb
    deps:
    - notebooks/ECommerce-Implicit-EDA.ipynb
    - data/external/ecommerce/data.csv
    outs:
    - data/interim/item_lookup.gz  
    - data/interim/item_lookup.csv  
    - data/interim/selected_invoices.gz  
    - data/interim/selected_invoices.csv  

  ecommerce_implicit_recommendation:
    cmd: >
      cd notebooks && jupyter nbconvert --to notebook --inplace --execute ECommerce-Implicit-Recommendation.ipynb
    deps:
    - notebooks/ECommerce-Implicit-Recommendation.ipynb
    - data/interim/selected_invoices.gz
    outs:
    - data/interim/user_factors.npy  
    - data/interim/item_factors.npy
    - data/interim/product_train.npy
