from .vipin20 import transform_vipin20
from .electronics import transform_electronics
from .brazilian import transform_brazilian
from .ecommerce import transform_ecommerce
from .jewelry import transform_jewelry
from .journey import transform_journey
from .retailrocket import transform_retailrocket
from .instacart import transform_instacart
from .bakery import transform_bakery