# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Training Pipelines

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: hsvai/product-rec:train

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run Pipelines
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        WANDB_API_KEY: ${{secrets.WANDB_API_KEY}}
      run: |
        kedro run --env vipin20 --pipeline vipin20
        kedro run --env brazilian --pipeline brazilian
        kedro run --env ecommerce --pipeline ecommerce
        kedro run --env jewelry --pipeline jewelry
        kedro run --env retailrocket --pipeline retailrocket
        kedro run --env journey --pipeline journey
#
#        // Too sparse and takes a very long time
#        kedro run --env electronics --pipeline electronics
